spring:
  application:
    name: hhbot
server:
  servlet:
    context-path: /api/v1/hhbot
  port: 8080
client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
  resume_id: ${RESUME_ID}
logging:
  level:
    ru.castroy10.hhbot.*: info
